"""Add portfolio and price history tables

Revision ID: 10c5287ef674
Revises: ace5a906266c
Create Date: 2025-06-26 02:29:48.331098

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10c5287ef674'
down_revision = 'ace5a906266c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('historical_price',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=32), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('price_usdt', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker', 'date', name='_ticker_date_uc')
    )
    with op.batch_alter_table('historical_price', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_historical_price_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_historical_price_ticker'), ['ticker'], unique=False)

    op.create_table('portfolio_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('total_value_rub', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('portfolio_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_portfolio_history_date'), ['date'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('portfolio_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_portfolio_history_date'))

    op.drop_table('portfolio_history')
    with op.batch_alter_table('historical_price', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_historical_price_ticker'))
        batch_op.drop_index(batch_op.f('ix_historical_price_date'))

    op.drop_table('historical_price')
    # ### end Alembic commands ###
