"""Add securities history and moex price cache tables

Revision ID: 18bc8cbd9a19
Revises: 10c5287ef674
Create Date: 2025-07-28 14:06:34.577062

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18bc8cbd9a19'
down_revision = '10c5287ef674'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('moex_historical_price',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('isin', sa.String(length=32), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('price_rub', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('isin', 'date', name='_moex_isin_date_uc')
    )
    with op.batch_alter_table('moex_historical_price', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_moex_historical_price_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_moex_historical_price_isin'), ['isin'], unique=False)

    op.create_table('securities_portfolio_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('total_value_rub', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('securities_portfolio_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_securities_portfolio_history_date'), ['date'], unique=True)

    with op.batch_alter_table('historical_price_cache', schema=None) as batch_op:
        batch_op.alter_column('last_updated',
               existing_type=sa.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('historical_price_cache', schema=None) as batch_op:
        batch_op.alter_column('last_updated',
               existing_type=sa.DATETIME(),
               nullable=False)

    with op.batch_alter_table('securities_portfolio_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_securities_portfolio_history_date'))

    op.drop_table('securities_portfolio_history')
    with op.batch_alter_table('moex_historical_price', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_moex_historical_price_isin'))
        batch_op.drop_index(batch_op.f('ix_moex_historical_price_date'))

    op.drop_table('moex_historical_price')
    # ### end Alembic commands ###
