"""Add JsonCache table

Revision ID: 694de7f7eb58
Revises: 18bc8cbd9a19
Create Date: 2025-07-28 17:56:49.806568

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '694de7f7eb58'
down_revision = '18bc8cbd9a19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('json_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cache_key', sa.String(length=128), nullable=False),
    sa.Column('json_data', sa.Text(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('json_cache', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_json_cache_cache_key'), ['cache_key'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('json_cache', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_json_cache_cache_key'))

    op.drop_table('json_cache')
    # ### end Alembic commands ###
