"""Add historical price cache table

Revision ID: a8fe5cd9f92b
Revises: 
Create Date: 2025-06-25 01:21:51.957176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8fe5cd9f92b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('historical_price_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=32), nullable=False),
    sa.Column('period', sa.String(length=10), nullable=False),
    sa.Column('change_percent', sa.Float(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker', 'period', name='_ticker_period_uc')
    )
    with op.batch_alter_table('historical_price_cache', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_historical_price_cache_period'), ['period'], unique=False)
        batch_op.create_index(batch_op.f('ix_historical_price_cache_ticker'), ['ticker'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('historical_price_cache', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_historical_price_cache_ticker'))
        batch_op.drop_index(batch_op.f('ix_historical_price_cache_period'))

    op.drop_table('historical_price_cache')
    # ### end Alembic commands ###
