"""Add last_tx_synced_at to InvestmentPlatform

Revision ID: ace5a906266c
Revises: a8fe5cd9f92b
Create Date: 2025-06-25 02:24:47.074243

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ace5a906266c'
down_revision = 'a8fe5cd9f92b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('investment_platform', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_tx_synced_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('investment_platform', schema=None) as batch_op:
        batch_op.drop_column('last_tx_synced_at')

    # ### end Alembic commands ###
