"""Add loyalty program models and fields to Transaction

Revision ID: ccf8bd98b87f
Revises: e20d78e8c5cb
Create Date: 2025-06-07 23:10:54.044377

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ccf8bd98b87f'
down_revision = 'e20d78e8c5cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('spent_loyalty_points', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('spent_loyalty_program_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'loyalty_program', ['spent_loyalty_program_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('spent_loyalty_program_id')
        batch_op.drop_column('spent_loyalty_points')

    # ### end Alembic commands ###
